package qunar.dev.task3.classfile;

/**
 * Tags in constant pool which can determine the class of elements in the pool
 * Created by Administrator on 2016/4/5.
 */
public enum ConstantPool_Tag {
    CONSTANT_CLASS, CONSTANT_DOUBLE, CONSTANT_FIELDREF, CONSTANT_FLOAT, CONSTANT_INTEGER, CONSTANT_INTERFACEMETHODREF, CONSTANT_INVOKEDYNAMIC, CONSTANT_LONG,
    CONSTANT_METHODHANDLE, CONSTANT_METHODREF, CONSTANT_METHODTYPE, CONSTANT_NAMEANDTYPE, CONSTANT_STRING, CONSTANT_UTF8
}
